title: Bulk Delete Tags
description: This Add-On  allows you to clear a tag or key/value pair from a set of documents. 
type: object
documents:
  - query
  - selected
properties:
  key:
    title: Key name of metadata you want to remove. 
    type: string
    description: If _tag is selected, all metadata under _tag will be deleted. Otherwise, if you provide a key only the metadata under that key will be removed. 
    default: _tag 
categories: 
  - bulk
